export default  {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    FETCH_USERS: 'FETCH_USERS',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    
  };