export default {

  //REDUX ACTIONS
  USER_LOGOUT: 'USER_LOGOUT',
  FETCH_ALL_USERS: 'FETCH_ALL_USERS',
  FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
  FETCH_ALL_USERS_ERROR: 'FETCH_ALL_USERS_ERROR',
  FETCHED_ACTIVE_USERS: 'FETCHED_ACTIVE_USERS',
  FETCH_ACTIVE_USERS: 'FETCH_ACTIVE_USERS',
  FETCH_ACTIVE_USERS_SUCCESS: 'FETCH_ACTIVE_USERS_SUCCESS',
  FETCH_ACTIVE_USERS_FAIL: 'FETCH_ACTIVE_USERS_FAIL',
  SET_CHAT_USER: 'SET_CHAT_USER',

  //SOCKET.IO
  ////Received by server
  ALL_USERS_GET: 'ALL_USERS_GET',
  ACTIVE_USERS_GET: 'ACTIVE_USERS_GET',
  CONNECT: 'CONNECT',
  DISCONNECT: 'disconnect',
  LOGOUT: 'LOGOUT',

  
  ////Received by client
  ACTIVE_USERS: 'ACTIVE_USERS',
  ALL_USERS: 'ALL_USERS',
};